export default [
    {
        id: 1,
        name: 'event 1',
        description: "Whatever leggings godard banh mi, man bun church-key raclette 3 wolf moon kitsch scenester brooklyn fanny pack tattooed. Ugh four loko flannel tonx, umami fixie mlkshk mumblecore. Retro hexagon slow-carb four dollar toast fam photo booth. Selvage kombucha flannel mumblecore enamel pin readymade intelligentsia",
        min_age: 0,
        max_age: 5,
        category: 'Child Minding',
        drop_in: false,
        other_information: "I'm baby hammock fanny pack photo booth taiyaki. Brooklyn shoreditch cloud bread kinfolk. Whatever slow-carb you probably haven't heard of them leggings tacos letterpress offal pinterest fingerstache. Authentic chambray fixie, pinterest enamel pin poutine forage roof party unicorn humblebrag mustache. Bicycle rights mumblecore adaptogen, vexillologist edison bulb kickstarter retro PBR&B normcore activated charcoal fingerstache twee green juice vegan.",
        days_of_the_week: ["Sun","Mon","Tues","Wed", "Thurs", "Fri", "Sat"],
        barcode: 1234,
        duration_in_weeks: 3,
        location: 'Woodstock Branch',
        max_participants: 20,
        start_time: {hour: 7, minute: 30, ante_meridian: 'PM'}, 
        end_time: {hour: 8, minute: 30, ante_meridian: 'PM'}, 
        start_date: 'May 5, 2022',
        end_date: 'June 30, 2022',
    },
    {
        id: 2,
        name: 'event 2',
        description: "Next level bespoke cornhole chambray, cold-pressed hashtag sustainable austin williamsburg tote bag waistcoat hexagon ugh. Keffiyeh fam hoodie, vegan mumblecore succulents celiac locavore. Tilde mustache pinterest, prism four loko fanny pack DIY tattooed. Bushwick affogato blue bottle, fixie vegan af hexagon yr mumblecore tbh cliche. Godard neutra banh mi, af farm-to-table put a bird on it pour-over gluten-free",
        min_age: 0,
        max_age: 5,
        category: 'Child Minding',
        days_of_the_week: ["Wed"],
        barcode: 4321,
        duration_in_weeks: 3,
        location: 'Woodstock Branch',
        max_participants: 20,
        start_time: {hour: 7, minute: 30, ante_meridian: 'PM'}, 
        end_time: {hour: 8, minute: 30, ante_meridian: 'PM'}, 
        start_date: 'May 5, 2022',
        end_date: 'June 30, 2022',

    },
    {
        id: 3,
        name: 'event 3',
        description: "Etsy paleo aesthetic quinoa kickstarter. Helvetica semiotics keffiyeh, quinoa plaid cliche heirloom chia enamel pin pop-up poutine. Meggings irony ennui glossier migas kombucha. Brooklyn photo booth enamel pin cold-pressed farm-to-table cardigan",
        min_age: 0,
        max_age: 5,
        category: 'Child Minding',
        days_of_the_week: ["Wed"],
        barcode: 5678,
        duration_in_weeks: 3,
        location: 'Woodstock Branch',
        max_participants: 20,
        start_time: {hour: 7, minute: 30, ante_meridian: 'PM'}, 
        end_time: {hour: 8, minute: 30, ante_meridian: 'PM'}, 
        start_date: 'May 5, 2022',
        end_date: 'June 30, 2022',
    },
    {
        id: 4,
        name: 'event 4',
        description: "I'm baby hammock fanny pack photo booth taiyaki. Brooklyn shoreditch cloud bread kinfolk. Whatever slow-carb you probably haven't heard of them leggings tacos letterpress offal pinterest fingerstache. Authentic chambray fixie, pinterest enamel pin poutine forage roof party unicorn humblebrag mustache. Bicycle rights mumblecore adaptogen, vexillologist edison bulb kickstarter retro PBR&B normcore activated charcoal fingerstache twee green juice vegan.",
        min_age: 0,
        max_age: 5,
        category: 'Child Minding',
        days_of_the_week: ["Wed"],
        barcode: 91011,
        duration_in_weeks: 3,
        location: 'Woodstock Branch',
        max_participants: 20,
        start_time: {hour: 7, minute: 30, ante_meridian: 'PM'}, 
        end_time: {hour: 8, minute: 30, ante_meridian: 'PM'}, 
        start_date: 'May 5, 2022',
        end_date: 'June 30, 2022',
    },
    {
        id: 5,
        name: 'event 5',
        description: "I'm baby hammock fanny pack photo booth taiyaki. Brooklyn shoreditch cloud bread kinfolk. Whatever slow-carb you probably haven't heard of them leggings tacos letterpress offal pinterest fingerstache. Authentic chambray fixie, pinterest enamel pin poutine forage roof party unicorn humblebrag mustache. Bicycle rights mumblecore adaptogen, vexillologist edison bulb kickstarter retro PBR&B normcore activated charcoal fingerstache twee green juice vegan.",
        min_age: 0,
        max_age: 5,
        category: 'Child Minding',
        days_of_the_week: ["Wed"],
        barcode: 13241526,
        duration_in_weeks: 3,
        location: 'Woodstock Branch',
        max_participants: 20,
        start_time: {hour: 7, minute: 30, ante_meridian: 'PM'}, 
        end_time: {hour: 8, minute: 30, ante_meridian: 'PM'}, 
        start_date: 'May 5, 2022',
        end_date: 'June 30, 2022',
    }

]