name: Deploy to AWS EC2

on: 
  push:
    branches: ["deploy-aws"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Create Env file
       run: |
         cd ./server/src/main/resources
         touch application.properties
         echo ${{ secrets.PROD_ENV }}
       shell: bash
     - name: Login to Docker Hub
       run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
     - name: Build Container image
       run: docker build -t ${{ secrets.DOCKER_REPO }}:latest .
     - name: Publish Docker image
       run: docker push ${{ secrets.DOCKER_REPO }}
  deploy:
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.HOSTNAME  }}
          USER_NAME: ${{ secrets.USER_NAME  }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

            #Now we have got the access of EC2 and we will start the deploy .
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker pull ${{ secrets.DOCKER_REPO }}:latest
            sudo docker stop server
            sudo docker rm server
            sudo docker run --detach --network="host" --name server ${{ secrets.DOCKER_REPO }}
            sudo systemctl restart nginx
          '